services:
  database:
    build: ./database
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: api_keys
    volumes:
    - ./postgres_data:/var/lib/postgresql/data
    networks:
      - backend  
    
  data-server:
    build: ./backend-data
    depends_on:
      - database
    ports:
      - "1025:1025"
    environment:
      FIRST_API: ${FIRST_API}
      SECOND_API: ${SECOND_API}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - backend
  
  data-auth:
    build: ./backend-auth
    depends_on:
      - database
    ports:
      - "1028:1028"
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - backend
networks:
  backend: